In [2]:
# 1 - One dimensional array using pandas
import pandas as pd
import numpy as np
data = [10,20,30,40,50]
arr = pd.Series(data)
print(arr)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
# 2 - Series into python list
s = pd.Series([10,20,30,40])
py_list = s.tolist()
print(py_list)
print(type(py_list))

[10, 20, 30, 40]
<class 'list'>

In [8]:
# 3 - Addition,subtraction and two pandas series
s1 = pd.Series([2,4,6,8,10])
s2 = pd.Series([1,3,5,7,9])
addition = s1 + s2
print("Addition")
print(addition)
subtraction = s1 - s2
print("Subtraction")
print(subtraction)
multiplication = s1 * s2
print("Multiplication")
print(multiplication)
print("Division")
division = s1/s2
print(division)

Addition
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtraction
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiplication
0     2
1    12
2    30
3    56
4    90
dtype: int64
Division
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [10]:
# 4 - Python program to get the powers of an array values
s1 = pd.Series([0, 1, 2, 3, 4, 5, 6])
s2 = pd.Series([1, 1, 3, 3, 3, 3, 3])
result = s1 ** s2
print("Original array")
print(s1.values)
print("First array elements raised to powers from second array, element-wise:")
print(result.values)

Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]

In [12]:
# 5 - To create a dataframe
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
                'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no',
                'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [ ]:
# 6 - Summary of basic information
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
                'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no',
                'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

In [14]:
# 7 - first three rows
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
                'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no',
                'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
df.head(3)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

In [ ]:
# 8 - Name and Score columns from data frame
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
                'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no',
                'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
selected_columns = df[['name','score']]
selected_columns

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

In [18]:
# 9 - Selecting the specified columns and rows from a given data frame
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
                'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no',
                'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data,index=labels)
result = df.loc[['b','d','f','g'],['name','score']]
result

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

In [25]:
# 10 - Select the rows where the number of attempts in the examination is greater than 2.
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
                'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no',
                'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data,index=labels)
# one method
res = df[df['attempts']> 2]
print(res)
# another method
res1 =df.loc[df['attempts'] > 2]
res1

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [ ]:
# 11 - Count the no of rows and columns of a data frame
rows = df.shape[0]
# shape[0] - gives rows count
# shape[1] - gives column count
columns = df.shape[1]
print(f"Rows count :{rows},Columns count :{columns}")

Rows count :10,Columns count :4

In [ ]:
# 12 -  Program to select the rows where the score is missing, i.e. is NaN
# isnull() - to find out the null values
missing = df[df['score'].isnull()]
print(missing)
# another method
mis = df.loc[df['score'].isna()]
print(mis)
# another method
miss = df[df['score'].isna()]
print(miss)

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

In [ ]:
# 13 -  Program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.
result = df[(df['attempts'] < 2) & (df['score'] > 15)]
result

    name  score  attempts qualify
j  Jonas   19.0         1     yes

In [46]:
# 14 - Python program to change the score in row 'd' to 11.5.
df.loc['d','score'] = 11.5
res = df.loc['d']
res

name        James
score        11.5
attempts        3
qualify        no
Name: d, dtype: object

In [ ]:
# 15 - Program to calculate the sum of the examination attempts by the students.
total = df['attempts'].sum()
# sum() - Automatically ignores missing values (NaN)
print(total)

19